version: '3.9'

services:
  neo4j:
    container_name: neo4j-example
    image: neo4j:4.4.2-enterprise
    ports:
      - 17474:7474
      - 17687:7687
#    volumes:
#      - ./var/neo4j/data:/data:delegated
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
